import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useAuthStore } from "../store";
import { useNoAuthRedirect } from "../hooks";

export default function Home() {
  const authStatus = useAuthStore(
    (store: any) => store.authStatus
  );

  const { loading } = useNoAuthRedirect();

  if (loading) {
    return <h1>loading...</h1>;
  }

  return (
    <>
      <Head>
        <title>NoteNexus</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto mt-20 grid h-fit w-11/12 gap-16 sm:grid-cols-1 lg:grid-cols-2">
          <div className="flex flex-col justify-center gap-2 space-y-3 sm:px-5 lg:px-14">
            <div className="space-y-4">
              <div className="">
                <h1 className="text-4xl font-extrabold text-[#242331]">
                  Meet your
                </h1>
                <h2 className="text-4xl font-extrabold text-[#242331]">
                  Note Talking App
                </h2>
              </div>

              <div className="">
                <p className="text-[#797979]">
                  Manage your daily tasks and
                  workflow in a modern way.
                </p>
              </div>
            </div>
            <div className="flex h-16 items-center gap-4 px-2">
              <Link
                className="w-fit rounded-md border bg-light-primary py-2 px-5 font-medium text-white"
                href="/signup"
              >
                Join Now
              </Link>
              <Link
                className="rounded-md border border-light-primary py-2 px-5 font-medium text-light-primary"
                href="/login"
              >
                Already had an account?
              </Link>
            </div>
          </div>
          <div className="relative aspect-video object-cover">
            <Image src="/notes.svg" alt="" fill />
          </div>
        </div>
      </main>
    </>
  );
}
